#!/usr/bin/env python3
"""
Generates the mirror demo build function (data/mirror/function/demo.mcfunction) and its companion
clear function. Run `python3 demo_world.py` after editing, then in-game `/reload` + `/function
mirror:demo` (or boot the prebuilt demo world via `./gradlew runTestWorld`).

The demo is a floating plaza of labelled stations, each showing a mirror configuration, with a
colourful backdrop on the player's side so the reflections have something to show besides the player.
Connection states (up/down/left/right) are computed exactly the way MirrorBlock does, so multi-block
mirrors merge correctly when placed by /setblock (which, unlike player placement, doesn't auto-connect).
"""
import os

FUNC_DIR = "src/main/resources/data/mirror/function"
FLOOR_Y = 64            # floor block; players stand at y=65
BASE_Y = 65             # mirror bottoms / walkway surface
WALL_Z = -3            # station back wall (mirrors hug it, facing south toward the walkway)
MIRROR_Z = -2          # south-facing mirror cells sit one block in front of the wall
SIGN_Z = 1             # labels in front of each station
SCENERY_Z = 13         # colourful backdrop south of the walkway (reflected in the mirrors)
X0, X1 = -8, 114       # plaza extent (x)
Z0, Z1 = -6, 16        # plaza extent (z)

# CCW / CW horizontal neighbour directions per facing - mirrors MirrorBlock.connectionProperty.
DIRS = {
    "south": ((1, 0, 0), (-1, 0, 0)),
    "north": ((-1, 0, 0), (1, 0, 0)),
    "east":  ((0, 0, -1), (0, 0, 1)),
    "west":  ((0, 0, 1), (0, 0, -1)),
}


def mirror_rect(cmds, facing, cells):
    """Place a connected mirror from a list of (x,y,z) cells, computing each cell's frame openings."""
    ccw, cw = DIRS[facing]
    s = set(cells)
    L = lambda b: str(b).lower()
    for (x, y, z) in cells:
        up = (x, y + 1, z) in s
        down = (x, y - 1, z) in s
        left = (x + ccw[0], y + ccw[1], z + ccw[2]) in s
        right = (x + cw[0], y + cw[1], z + cw[2]) in s
        # diagonals (for inner-corner frame pieces): up/down combined with the left/right direction
        ul = (x + ccw[0], y + 1 + ccw[1], z + ccw[2]) in s
        ur = (x + cw[0], y + 1 + cw[1], z + cw[2]) in s
        dl = (x + ccw[0], y - 1 + ccw[1], z + ccw[2]) in s
        dr = (x + cw[0], y - 1 + cw[1], z + cw[2]) in s
        st = "facing=%s,up=%s,down=%s,left=%s,right=%s,ul=%s,ur=%s,dl=%s,dr=%s" % (
            facing, L(up), L(down), L(left), L(right), L(ul), L(ur), L(dl), L(dr))
        cmds.append("setblock %d %d %d mirror:mirror[%s]" % (x, y, z, st))


def rect_cells(x, y, z, w, h, axis):
    """w×h cells anchored at (x,y) bottom-left, growing +y and along axis ('x' or 'z')."""
    out = []
    for r in range(h):
        for c in range(w):
            if axis == "x":
                out.append((x + c, y + r, z))
            else:
                out.append((x, y + r, z + c))
    return out


def sign(cmds, x, y, z, lines, rotation=0):
    msgs = ",".join('"%s"' % ln for ln in (lines + ["", "", "", ""])[:4])
    cmds.append('setblock %d %d %d minecraft:oak_sign[rotation=%d]{front_text:{messages:[%s]}}'
                % (x, y, z, rotation, msgs))


def wall(cmds, x0, x1, y0, y1, z, block="minecraft:deepslate_bricks"):
    cmds.append("fill %d %d %d %d %d %d %s" % (x0, y0, z, x1, y1, z, block))


def build():
    c = []
    c.append("# === Mirror mod demo -- generated by demo_world.py ===")
    # NOTE: no gamerule/weather/time here. A mod-provided function is parsed before the gamerule command's
    # registry-built argument tree exists, so `gamerule ...` fails to load the whole function. World
    # conditions for the prebuilt demo are set over RCON instead; in your own world set them to taste.
    # Clear the build volume, then lay the floor.
    c.append("fill %d %d %d %d %d %d air" % (X0, FLOOR_Y, Z0, X1, BASE_Y + 12, Z1))
    c.append("fill %d %d %d %d %d %d minecraft:smooth_quartz" % (X0, FLOOR_Y, Z0, X1, FLOOR_Y, Z1))
    # A subtle carpet runner along the walkway.
    c.append("fill %d %d %d %d %d %d minecraft:light_blue_carpet" % (X0 + 1, BASE_Y, 4, X1 - 1, BASE_Y, 6))

    # Colourful backdrop wall on the player's side, so every mirror reflects something vivid.
    palette = ["red", "orange", "yellow", "lime", "green", "cyan", "light_blue", "blue", "purple",
               "magenta", "pink", "white"]
    for i, x in enumerate(range(X0, X1 + 1)):
        col = palette[(x // 3) % len(palette)]
        c.append("fill %d %d %d %d %d %d minecraft:%s_concrete"
                 % (x, BASE_Y, SCENERY_Z, x, BASE_Y + 4, SCENERY_Z, col))
    # A few sea lanterns + quartz pillars in front of the backdrop for depth in the reflection.
    for x in range(X0 + 4, X1, 16):
        c.append("fill %d %d %d %d %d %d minecraft:quartz_pillar" % (x, BASE_Y, SCENERY_Z - 3, x, BASE_Y + 3, SCENERY_Z - 3))
        c.append("setblock %d %d %d minecraft:sea_lantern" % (x, BASE_Y + 4, SCENERY_Z - 3))

    # ---- Stations (all south-facing unless noted). Each: back wall + mirror(s) + label sign. ----
    def station_wall(x_center, half_w, top_y):
        wall(c, x_center - half_w, x_center + half_w, FLOOR_Y, top_y, WALL_Z)

    # 1) 1x1
    x = 0
    station_wall(x, 2, BASE_Y + 3)
    mirror_rect(c, "south", [(x, BASE_Y, MIRROR_Z)])
    sign(c, x, BASE_Y, SIGN_Z, ["1x1", "single mirror"])

    # 2) 1x2 tall
    x = 12
    station_wall(x, 2, BASE_Y + 4)
    mirror_rect(c, "south", rect_cells(x, BASE_Y, MIRROR_Z, 1, 2, "x"))
    sign(c, x, BASE_Y, SIGN_Z, ["1x2", "tall", "auto-merged"])

    # 3) 2x1 wide
    x = 24
    station_wall(x, 3, BASE_Y + 3)
    mirror_rect(c, "south", rect_cells(x, BASE_Y, MIRROR_Z, 2, 1, "x"))
    sign(c, x, BASE_Y, SIGN_Z, ["2x1", "wide"])

    # 4) 2x2
    x = 36
    station_wall(x, 3, BASE_Y + 4)
    mirror_rect(c, "south", rect_cells(x, BASE_Y, MIRROR_Z, 2, 2, "x"))
    sign(c, x, BASE_Y, SIGN_Z, ["2x2", "square"])

    # 5) 4x3 big wall (one reflection pass for the whole thing)
    x = 49
    station_wall(x - 1, 4, BASE_Y + 5)
    mirror_rect(c, "south", rect_cells(x - 1, BASE_Y, MIRROR_Z, 4, 3, "x"))
    sign(c, x - 1, BASE_Y, SIGN_Z, ["4x3 wall", "ONE reflection", "pass"])

    # 6) Corner - two perpendicular mirrors (two planes rendering at once = the multi-plane fix).
    # Stand in the corner and look NW: south-facing wall to your north, east-facing wall to your west.
    x = 62
    station_wall(x, 2, BASE_Y + 4)  # north wall (south-facing mirror)
    mirror_rect(c, "south", rect_cells(x, BASE_Y, MIRROR_Z, 2, 2, "x"))
    # west wall at x-4; east-facing 2x2 hugs it at x-3, cells along adjacent z
    c.append("fill %d %d %d %d %d %d minecraft:deepslate_bricks" % (x - 4, FLOOR_Y, MIRROR_Z, x - 4, BASE_Y + 4, MIRROR_Z + 1))
    mirror_rect(c, "east", [(x - 3, yy, zz) for yy in (BASE_Y, BASE_Y + 1) for zz in (MIRROR_Z, MIRROR_Z + 1)])
    sign(c, x, BASE_Y, SIGN_Z, ["Corner", "two angles", "at once"])

    # 7) Occlusion - a 2x2 with a pillar + entity in front
    x = 75
    station_wall(x, 3, BASE_Y + 4)
    mirror_rect(c, "south", rect_cells(x, BASE_Y, MIRROR_Z, 2, 2, "x"))
    c.append("fill %d %d %d %d %d %d minecraft:stone_bricks" % (x + 3, BASE_Y, SIGN_Z + 1, x + 3, BASE_Y + 2, SIGN_Z + 1))
    c.append("summon minecraft:armor_stand %d %d %d {NoGravity:1b,Invulnerable:1b,ShowArms:1b}" % (x, BASE_Y, SIGN_Z + 1))
    sign(c, x, BASE_Y, SIGN_Z, ["Occlusion", "blocked by", "stuff in front"])

    # 8) Dressing room - three mirrors in a U (see yourself from 3 sides)
    x = 90
    # back (south-facing)
    station_wall(x, 2, BASE_Y + 4)
    mirror_rect(c, "south", rect_cells(x, BASE_Y, MIRROR_Z, 2, 2, "x"))
    # left wall (east-facing) at x-2
    c.append("fill %d %d %d %d %d %d minecraft:deepslate_bricks" % (x - 3, FLOOR_Y, MIRROR_Z, x - 3, BASE_Y + 4, SIGN_Z + 2))
    mirror_rect(c, "east", [(x - 2, yy, zz) for yy in (BASE_Y, BASE_Y + 1) for zz in (MIRROR_Z + 1, MIRROR_Z + 2)])
    # right wall (west-facing) at x+3
    c.append("fill %d %d %d %d %d %d minecraft:deepslate_bricks" % (x + 3, FLOOR_Y, MIRROR_Z, x + 3, BASE_Y + 4, SIGN_Z + 2))
    mirror_rect(c, "west", [(x + 2, yy, zz) for yy in (BASE_Y, BASE_Y + 1) for zz in (MIRROR_Z + 1, MIRROR_Z + 2)])
    sign(c, x, BASE_Y, SIGN_Z + 2, ["Dressing room", "3 angles of you"])

    # 9) L-shape - same-facing merge with an inner (concave) corner; that corner keeps a frame piece.
    x = 104
    station_wall(x, 3, BASE_Y + 4)
    mirror_rect(c, "south", [(x, BASE_Y + 1, MIRROR_Z), (x, BASE_Y, MIRROR_Z), (x + 1, BASE_Y, MIRROR_Z)])
    sign(c, x, BASE_Y, SIGN_Z, ["L-shape", "inner corner", "keeps its frame"])

    # Intro sign + spawn near the first station.
    sign(c, -4, BASE_Y, 6, ["MIRROR DEMO", "walk east ->", "stations labelled"], rotation=0)
    c.append("setworldspawn -4 %d 7" % BASE_Y)
    c.append('tellraw @a {"text":"Mirror demo built. Walk east along the plaza.","color":"aqua"}')
    # Release the force-load taken by mirror:demo now that everything is placed.
    c.append("forceload remove all")
    return c


# Stress arena, off east of the plaza. A staircase of south-facing panels, each at a UNIQUE perpendicular
# distance, so every panel is its OWN reflection plane - standing south and looking north puts them all on
# screen at once, the worst case for the renderer (it picks the nearest MAX_PLANES and re-renders the world
# once per chosen plane). Use it with F3 + the [mirror perf] log to see the cost.
STRESS_X, STRESS_Z = 200, 0
STRESS_REGION = (STRESS_X - 4, STRESS_Z - 28, STRESS_X + 28, STRESS_Z + 16)


def stress_build():
    c = []
    bx, bz = STRESS_X, STRESS_Z
    top = BASE_Y + 8
    c.append("fill %d %d %d %d %d %d air" % (bx - 4, FLOOR_Y, bz - 28, bx + 28, top, bz + 16))
    c.append("fill %d %d %d %d %d %d minecraft:smooth_quartz" % (bx - 4, FLOOR_Y, bz - 28, bx + 28, FLOOR_Y, bz + 16))
    # Colourful backdrop SOUTH of the viewer so the south-facing panels reflect something vivid.
    palette = ["red", "orange", "yellow", "lime", "green", "cyan", "light_blue", "blue", "purple",
               "magenta", "pink", "white"]
    for x in range(bx - 4, bx + 28):
        col = palette[(x // 3) % len(palette)]
        c.append("fill %d %d %d %d %d %d minecraft:%s_concrete" % (x, BASE_Y, bz + 14, x, BASE_Y + 6, bz + 14, col))
    # 8 panels, each on its own plane (unique z), stepped in x so all are visible at once.
    for i in range(8):
        mirror_rect(c, "south", rect_cells(bx + i * 3, BASE_Y, bz - 2 - i * 3, 2, 3, "x"))
    sign(c, bx, BASE_Y, bz + 1, ["STRESS ARENA", "8 mirror planes", "F3 + [mirror perf]"])
    c.append("tp @p %d %d %d 180 0" % (bx + 6, BASE_Y, bz + 6))  # stand south of the panels, facing north
    c.append('tellraw @a {"text":"Stress arena: face north at the panels; watch FPS (F3) and the [mirror perf] log.","color":"gold"}')
    c.append("forceload remove all")
    return c


def write(name, lines):
    with open(os.path.join(FUNC_DIR, name), "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    os.makedirs(FUNC_DIR, exist_ok=True)
    # `mirror:demo` is the entry point: force-load the build region, then schedule the actual build a
    # couple seconds later so the chunks are live first (a one-tick function can't force-load AND build
    # in the same tick). Works the same in-game and when driven headlessly from the dedicated server.
    region = "%d %d %d %d" % (X0, Z0, X1, Z1)
    demo = [
        "# Mirror demo entry - force-load the plaza, then build it once chunks are live.",
        "forceload add %s" % region,
        'tellraw @a {"text":"Building mirror demo (chunks loading)...","color":"gray"}',
        "schedule function mirror:build 40t",
    ]
    write("demo.mcfunction", demo)
    write("build.mcfunction", build())
    write("clear.mcfunction", [
        "# Wipe the demo build volume (best-effort; run while standing in the plaza).",
        "forceload add %s" % region,
        "fill %d %d %d %d %d %d air" % (X0, FLOOR_Y, Z0, X1, BASE_Y + 12, Z1),
        "forceload remove all",
    ])
    # `mirror:stress` - force-load the arena, then build + teleport in once chunks are live.
    write("stress.mcfunction", [
        "# Stress-arena entry - force-load, then build once chunks are live.",
        "forceload add %d %d %d %d" % STRESS_REGION,
        'tellraw @a {"text":"Building stress arena (chunks loading)...","color":"gray"}',
        "schedule function mirror:stress_build 40t",
    ])
    write("stress_build.mcfunction", stress_build())
    print("wrote demo.mcfunction (entry) + build.mcfunction (%d cmds) + clear.mcfunction + stress.mcfunction" % len(build()))


if __name__ == "__main__":
    main()
