# === Mirror mod demo -- generated by demo_world.py ===
fill -8 64 -6 114 77 16 air
fill -8 64 -6 114 64 16 minecraft:smooth_quartz
fill -7 65 4 113 65 6 minecraft:light_blue_carpet
fill -8 65 13 -8 69 13 minecraft:magenta_concrete
fill -7 65 13 -7 69 13 minecraft:magenta_concrete
fill -6 65 13 -6 69 13 minecraft:pink_concrete
fill -5 65 13 -5 69 13 minecraft:pink_concrete
fill -4 65 13 -4 69 13 minecraft:pink_concrete
fill -3 65 13 -3 69 13 minecraft:white_concrete
fill -2 65 13 -2 69 13 minecraft:white_concrete
fill -1 65 13 -1 69 13 minecraft:white_concrete
fill 0 65 13 0 69 13 minecraft:red_concrete
fill 1 65 13 1 69 13 minecraft:red_concrete
fill 2 65 13 2 69 13 minecraft:red_concrete
fill 3 65 13 3 69 13 minecraft:orange_concrete
fill 4 65 13 4 69 13 minecraft:orange_concrete
fill 5 65 13 5 69 13 minecraft:orange_concrete
fill 6 65 13 6 69 13 minecraft:yellow_concrete
fill 7 65 13 7 69 13 minecraft:yellow_concrete
fill 8 65 13 8 69 13 minecraft:yellow_concrete
fill 9 65 13 9 69 13 minecraft:lime_concrete
fill 10 65 13 10 69 13 minecraft:lime_concrete
fill 11 65 13 11 69 13 minecraft:lime_concrete
fill 12 65 13 12 69 13 minecraft:green_concrete
fill 13 65 13 13 69 13 minecraft:green_concrete
fill 14 65 13 14 69 13 minecraft:green_concrete
fill 15 65 13 15 69 13 minecraft:cyan_concrete
fill 16 65 13 16 69 13 minecraft:cyan_concrete
fill 17 65 13 17 69 13 minecraft:cyan_concrete
fill 18 65 13 18 69 13 minecraft:light_blue_concrete
fill 19 65 13 19 69 13 minecraft:light_blue_concrete
fill 20 65 13 20 69 13 minecraft:light_blue_concrete
fill 21 65 13 21 69 13 minecraft:blue_concrete
fill 22 65 13 22 69 13 minecraft:blue_concrete
fill 23 65 13 23 69 13 minecraft:blue_concrete
fill 24 65 13 24 69 13 minecraft:purple_concrete
fill 25 65 13 25 69 13 minecraft:purple_concrete
fill 26 65 13 26 69 13 minecraft:purple_concrete
fill 27 65 13 27 69 13 minecraft:magenta_concrete
fill 28 65 13 28 69 13 minecraft:magenta_concrete
fill 29 65 13 29 69 13 minecraft:magenta_concrete
fill 30 65 13 30 69 13 minecraft:pink_concrete
fill 31 65 13 31 69 13 minecraft:pink_concrete
fill 32 65 13 32 69 13 minecraft:pink_concrete
fill 33 65 13 33 69 13 minecraft:white_concrete
fill 34 65 13 34 69 13 minecraft:white_concrete
fill 35 65 13 35 69 13 minecraft:white_concrete
fill 36 65 13 36 69 13 minecraft:red_concrete
fill 37 65 13 37 69 13 minecraft:red_concrete
fill 38 65 13 38 69 13 minecraft:red_concrete
fill 39 65 13 39 69 13 minecraft:orange_concrete
fill 40 65 13 40 69 13 minecraft:orange_concrete
fill 41 65 13 41 69 13 minecraft:orange_concrete
fill 42 65 13 42 69 13 minecraft:yellow_concrete
fill 43 65 13 43 69 13 minecraft:yellow_concrete
fill 44 65 13 44 69 13 minecraft:yellow_concrete
fill 45 65 13 45 69 13 minecraft:lime_concrete
fill 46 65 13 46 69 13 minecraft:lime_concrete
fill 47 65 13 47 69 13 minecraft:lime_concrete
fill 48 65 13 48 69 13 minecraft:green_concrete
fill 49 65 13 49 69 13 minecraft:green_concrete
fill 50 65 13 50 69 13 minecraft:green_concrete
fill 51 65 13 51 69 13 minecraft:cyan_concrete
fill 52 65 13 52 69 13 minecraft:cyan_concrete
fill 53 65 13 53 69 13 minecraft:cyan_concrete
fill 54 65 13 54 69 13 minecraft:light_blue_concrete
fill 55 65 13 55 69 13 minecraft:light_blue_concrete
fill 56 65 13 56 69 13 minecraft:light_blue_concrete
fill 57 65 13 57 69 13 minecraft:blue_concrete
fill 58 65 13 58 69 13 minecraft:blue_concrete
fill 59 65 13 59 69 13 minecraft:blue_concrete
fill 60 65 13 60 69 13 minecraft:purple_concrete
fill 61 65 13 61 69 13 minecraft:purple_concrete
fill 62 65 13 62 69 13 minecraft:purple_concrete
fill 63 65 13 63 69 13 minecraft:magenta_concrete
fill 64 65 13 64 69 13 minecraft:magenta_concrete
fill 65 65 13 65 69 13 minecraft:magenta_concrete
fill 66 65 13 66 69 13 minecraft:pink_concrete
fill 67 65 13 67 69 13 minecraft:pink_concrete
fill 68 65 13 68 69 13 minecraft:pink_concrete
fill 69 65 13 69 69 13 minecraft:white_concrete
fill 70 65 13 70 69 13 minecraft:white_concrete
fill 71 65 13 71 69 13 minecraft:white_concrete
fill 72 65 13 72 69 13 minecraft:red_concrete
fill 73 65 13 73 69 13 minecraft:red_concrete
fill 74 65 13 74 69 13 minecraft:red_concrete
fill 75 65 13 75 69 13 minecraft:orange_concrete
fill 76 65 13 76 69 13 minecraft:orange_concrete
fill 77 65 13 77 69 13 minecraft:orange_concrete
fill 78 65 13 78 69 13 minecraft:yellow_concrete
fill 79 65 13 79 69 13 minecraft:yellow_concrete
fill 80 65 13 80 69 13 minecraft:yellow_concrete
fill 81 65 13 81 69 13 minecraft:lime_concrete
fill 82 65 13 82 69 13 minecraft:lime_concrete
fill 83 65 13 83 69 13 minecraft:lime_concrete
fill 84 65 13 84 69 13 minecraft:green_concrete
fill 85 65 13 85 69 13 minecraft:green_concrete
fill 86 65 13 86 69 13 minecraft:green_concrete
fill 87 65 13 87 69 13 minecraft:cyan_concrete
fill 88 65 13 88 69 13 minecraft:cyan_concrete
fill 89 65 13 89 69 13 minecraft:cyan_concrete
fill 90 65 13 90 69 13 minecraft:light_blue_concrete
fill 91 65 13 91 69 13 minecraft:light_blue_concrete
fill 92 65 13 92 69 13 minecraft:light_blue_concrete
fill 93 65 13 93 69 13 minecraft:blue_concrete
fill 94 65 13 94 69 13 minecraft:blue_concrete
fill 95 65 13 95 69 13 minecraft:blue_concrete
fill 96 65 13 96 69 13 minecraft:purple_concrete
fill 97 65 13 97 69 13 minecraft:purple_concrete
fill 98 65 13 98 69 13 minecraft:purple_concrete
fill 99 65 13 99 69 13 minecraft:magenta_concrete
fill 100 65 13 100 69 13 minecraft:magenta_concrete
fill 101 65 13 101 69 13 minecraft:magenta_concrete
fill 102 65 13 102 69 13 minecraft:pink_concrete
fill 103 65 13 103 69 13 minecraft:pink_concrete
fill 104 65 13 104 69 13 minecraft:pink_concrete
fill 105 65 13 105 69 13 minecraft:white_concrete
fill 106 65 13 106 69 13 minecraft:white_concrete
fill 107 65 13 107 69 13 minecraft:white_concrete
fill 108 65 13 108 69 13 minecraft:red_concrete
fill 109 65 13 109 69 13 minecraft:red_concrete
fill 110 65 13 110 69 13 minecraft:red_concrete
fill 111 65 13 111 69 13 minecraft:orange_concrete
fill 112 65 13 112 69 13 minecraft:orange_concrete
fill 113 65 13 113 69 13 minecraft:orange_concrete
fill 114 65 13 114 69 13 minecraft:yellow_concrete
fill -4 65 10 -4 68 10 minecraft:quartz_pillar
setblock -4 69 10 minecraft:sea_lantern
fill 12 65 10 12 68 10 minecraft:quartz_pillar
setblock 12 69 10 minecraft:sea_lantern
fill 28 65 10 28 68 10 minecraft:quartz_pillar
setblock 28 69 10 minecraft:sea_lantern
fill 44 65 10 44 68 10 minecraft:quartz_pillar
setblock 44 69 10 minecraft:sea_lantern
fill 60 65 10 60 68 10 minecraft:quartz_pillar
setblock 60 69 10 minecraft:sea_lantern
fill 76 65 10 76 68 10 minecraft:quartz_pillar
setblock 76 69 10 minecraft:sea_lantern
fill 92 65 10 92 68 10 minecraft:quartz_pillar
setblock 92 69 10 minecraft:sea_lantern
fill 108 65 10 108 68 10 minecraft:quartz_pillar
setblock 108 69 10 minecraft:sea_lantern
fill -2 64 -3 2 68 -3 minecraft:deepslate_bricks
setblock 0 65 -2 mirror:mirror[facing=south,up=false,down=false,left=false,right=false,ul=false,ur=false,dl=false,dr=false]
setblock 0 65 1 minecraft:oak_sign[rotation=0]{front_text:{messages:["1x1","single mirror","",""]}}
fill 10 64 -3 14 69 -3 minecraft:deepslate_bricks
setblock 12 65 -2 mirror:mirror[facing=south,up=true,down=false,left=false,right=false,ul=false,ur=false,dl=false,dr=false]
setblock 12 66 -2 mirror:mirror[facing=south,up=false,down=true,left=false,right=false,ul=false,ur=false,dl=false,dr=false]
setblock 12 65 1 minecraft:oak_sign[rotation=0]{front_text:{messages:["1x2","tall","auto-merged",""]}}
fill 21 64 -3 27 68 -3 minecraft:deepslate_bricks
setblock 24 65 -2 mirror:mirror[facing=south,up=false,down=false,left=true,right=false,ul=false,ur=false,dl=false,dr=false]
setblock 25 65 -2 mirror:mirror[facing=south,up=false,down=false,left=false,right=true,ul=false,ur=false,dl=false,dr=false]
setblock 24 65 1 minecraft:oak_sign[rotation=0]{front_text:{messages:["2x1","wide","",""]}}
fill 33 64 -3 39 69 -3 minecraft:deepslate_bricks
setblock 36 65 -2 mirror:mirror[facing=south,up=true,down=false,left=true,right=false,ul=true,ur=false,dl=false,dr=false]
setblock 37 65 -2 mirror:mirror[facing=south,up=true,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 36 66 -2 mirror:mirror[facing=south,up=false,down=true,left=true,right=false,ul=false,ur=false,dl=true,dr=false]
setblock 37 66 -2 mirror:mirror[facing=south,up=false,down=true,left=false,right=true,ul=false,ur=false,dl=false,dr=true]
setblock 36 65 1 minecraft:oak_sign[rotation=0]{front_text:{messages:["2x2","square","",""]}}
fill 44 64 -3 52 70 -3 minecraft:deepslate_bricks
setblock 48 65 -2 mirror:mirror[facing=south,up=true,down=false,left=true,right=false,ul=true,ur=false,dl=false,dr=false]
setblock 49 65 -2 mirror:mirror[facing=south,up=true,down=false,left=true,right=true,ul=true,ur=true,dl=false,dr=false]
setblock 50 65 -2 mirror:mirror[facing=south,up=true,down=false,left=true,right=true,ul=true,ur=true,dl=false,dr=false]
setblock 51 65 -2 mirror:mirror[facing=south,up=true,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 48 66 -2 mirror:mirror[facing=south,up=true,down=true,left=true,right=false,ul=true,ur=false,dl=true,dr=false]
setblock 49 66 -2 mirror:mirror[facing=south,up=true,down=true,left=true,right=true,ul=true,ur=true,dl=true,dr=true]
setblock 50 66 -2 mirror:mirror[facing=south,up=true,down=true,left=true,right=true,ul=true,ur=true,dl=true,dr=true]
setblock 51 66 -2 mirror:mirror[facing=south,up=true,down=true,left=false,right=true,ul=false,ur=true,dl=false,dr=true]
setblock 48 67 -2 mirror:mirror[facing=south,up=false,down=true,left=true,right=false,ul=false,ur=false,dl=true,dr=false]
setblock 49 67 -2 mirror:mirror[facing=south,up=false,down=true,left=true,right=true,ul=false,ur=false,dl=true,dr=true]
setblock 50 67 -2 mirror:mirror[facing=south,up=false,down=true,left=true,right=true,ul=false,ur=false,dl=true,dr=true]
setblock 51 67 -2 mirror:mirror[facing=south,up=false,down=true,left=false,right=true,ul=false,ur=false,dl=false,dr=true]
setblock 48 65 1 minecraft:oak_sign[rotation=0]{front_text:{messages:["4x3 wall","ONE reflection","pass",""]}}
fill 60 64 -3 64 69 -3 minecraft:deepslate_bricks
setblock 62 65 -2 mirror:mirror[facing=south,up=true,down=false,left=true,right=false,ul=true,ur=false,dl=false,dr=false]
setblock 63 65 -2 mirror:mirror[facing=south,up=true,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 62 66 -2 mirror:mirror[facing=south,up=false,down=true,left=true,right=false,ul=false,ur=false,dl=true,dr=false]
setblock 63 66 -2 mirror:mirror[facing=south,up=false,down=true,left=false,right=true,ul=false,ur=false,dl=false,dr=true]
fill 58 64 -2 58 69 -1 minecraft:deepslate_bricks
setblock 59 65 -2 mirror:mirror[facing=east,up=true,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 59 65 -1 mirror:mirror[facing=east,up=true,down=false,left=true,right=false,ul=true,ur=false,dl=false,dr=false]
setblock 59 66 -2 mirror:mirror[facing=east,up=false,down=true,left=false,right=true,ul=false,ur=false,dl=false,dr=true]
setblock 59 66 -1 mirror:mirror[facing=east,up=false,down=true,left=true,right=false,ul=false,ur=false,dl=true,dr=false]
setblock 62 65 1 minecraft:oak_sign[rotation=0]{front_text:{messages:["Corner","two angles","at once",""]}}
fill 72 64 -3 78 69 -3 minecraft:deepslate_bricks
setblock 75 65 -2 mirror:mirror[facing=south,up=true,down=false,left=true,right=false,ul=true,ur=false,dl=false,dr=false]
setblock 76 65 -2 mirror:mirror[facing=south,up=true,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 75 66 -2 mirror:mirror[facing=south,up=false,down=true,left=true,right=false,ul=false,ur=false,dl=true,dr=false]
setblock 76 66 -2 mirror:mirror[facing=south,up=false,down=true,left=false,right=true,ul=false,ur=false,dl=false,dr=true]
fill 78 65 2 78 67 2 minecraft:stone_bricks
summon minecraft:armor_stand 75 65 2 {NoGravity:1b,Invulnerable:1b,ShowArms:1b}
setblock 75 65 1 minecraft:oak_sign[rotation=0]{front_text:{messages:["Occlusion","blocked by","stuff in front",""]}}
fill 88 64 -3 92 69 -3 minecraft:deepslate_bricks
setblock 90 65 -2 mirror:mirror[facing=south,up=true,down=false,left=true,right=false,ul=true,ur=false,dl=false,dr=false]
setblock 91 65 -2 mirror:mirror[facing=south,up=true,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 90 66 -2 mirror:mirror[facing=south,up=false,down=true,left=true,right=false,ul=false,ur=false,dl=true,dr=false]
setblock 91 66 -2 mirror:mirror[facing=south,up=false,down=true,left=false,right=true,ul=false,ur=false,dl=false,dr=true]
fill 87 64 -2 87 69 3 minecraft:deepslate_bricks
setblock 88 65 -1 mirror:mirror[facing=east,up=true,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 88 65 0 mirror:mirror[facing=east,up=true,down=false,left=true,right=false,ul=true,ur=false,dl=false,dr=false]
setblock 88 66 -1 mirror:mirror[facing=east,up=false,down=true,left=false,right=true,ul=false,ur=false,dl=false,dr=true]
setblock 88 66 0 mirror:mirror[facing=east,up=false,down=true,left=true,right=false,ul=false,ur=false,dl=true,dr=false]
fill 93 64 -2 93 69 3 minecraft:deepslate_bricks
setblock 92 65 -1 mirror:mirror[facing=west,up=true,down=false,left=true,right=false,ul=true,ur=false,dl=false,dr=false]
setblock 92 65 0 mirror:mirror[facing=west,up=true,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 92 66 -1 mirror:mirror[facing=west,up=false,down=true,left=true,right=false,ul=false,ur=false,dl=true,dr=false]
setblock 92 66 0 mirror:mirror[facing=west,up=false,down=true,left=false,right=true,ul=false,ur=false,dl=false,dr=true]
setblock 90 65 3 minecraft:oak_sign[rotation=0]{front_text:{messages:["Dressing room","3 angles of you","",""]}}
fill 101 64 -3 107 69 -3 minecraft:deepslate_bricks
setblock 104 66 -2 mirror:mirror[facing=south,up=false,down=true,left=false,right=false,ul=false,ur=false,dl=true,dr=false]
setblock 104 65 -2 mirror:mirror[facing=south,up=true,down=false,left=true,right=false,ul=false,ur=false,dl=false,dr=false]
setblock 105 65 -2 mirror:mirror[facing=south,up=false,down=false,left=false,right=true,ul=false,ur=true,dl=false,dr=false]
setblock 104 65 1 minecraft:oak_sign[rotation=0]{front_text:{messages:["L-shape","inner corner","keeps its frame",""]}}
setblock -4 65 6 minecraft:oak_sign[rotation=0]{front_text:{messages:["MIRROR DEMO","walk east ->","stations labelled",""]}}
setworldspawn -4 65 7
tellraw @a {"text":"Mirror demo built. Walk east along the plaza.","color":"aqua"}
forceload remove all
